name: 🌳
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    # Pre version is released in https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240604.1
    # It is not yet appeared, so I want to watch.
    - cron: '1 2,14 * * *'
  workflow_dispatch:

jobs:
  tree:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-22.04', 'ubuntu-20.04']
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Inspect depednency
        run: |
          command -v tree
          tree --version
      - run: tree
